# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=200)),
                ('started_on', models.DateField()),
                ('due_on', models.DateField()),
                ('owner', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
    ]
