apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: django-data-pv
          persistentVolumeClaim:
           claimName: django-data-pv-claim
      containers:
        - name: django
          image: curtis911/todo-list-full-stack-django
          volumeMounts:
            - mountPath: "/src"
              name: django-data-pv
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_HOST
              value: "db"
            - name: FRONTEND_IP
              value: "192.168.39.121:30889"
            - name: PGADMIN_IP
              value: "192.168.39.121:31566"
        - name: nginx
          image: curtis911/todo-list-full-stack-nginx
          volumeMounts:
            - mountPath: "/src"
              name: django-data-pv
          ports:
            - containerPort: 8888
