apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: django-data-pv
          persistentVolumeClaim:
           claimName: django-data-pv-claim
      containers:
        - name: django
          image: curtis911/todo-list-full-stack-django
          volumeMounts:
            - mountPath: "/src"
              name: django-data-pv
