kind: PersistentVolume
apiVersion: v1
metadata:
  name: django-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/todo-list-full-stack/todo-list-django/src"

