apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: curtis911/todo-list-full-stack-frontend
          env:
            - name: TODO_BACKEND_URL
              # ex: http://192.168.39.121:32467/api/todo-list/
              value: "http://192.168.39.121:32467/api/todo-list/"
